name: Windows Docker Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 myapp:latest
          sleep 10 # Wait for container to start

      - name: Echo Wallpaper
        run: docker exec <container-id> powershell -Command "(New-Object -ComObject 'WScript.Shell').Wallpaper"
